spring:
  application:
    name: repair-platform
  profiles:
    # 当前生效的环境配置
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.lhl.rp.bean

token:
  # 过期 Token 清理周期（秒）
  cleanup-interval-second: 60
  # Token 有效期（秒）
  ttl-second: 7200