server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auto_repair_system
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

cors:
  # 允许哪些源访问
  allowed-origins: http://localhost:5173/
  # 允许哪些方法
  allowed-methods: GET, POST, PUT, DELETE
  # 允许携带哪些头部信息
  allowed-headers: Authorization, Content-Type, X-Requested-With
  # 允许携带凭证
  allow-credentials: true

minio:
  # MinIO 服务地址
  endpoint: http://localhost:9000/
  # 访问密钥
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    # 头像存储桶
    avatar: repair-sys-user-avatars